## Step 1: Setup (folder, data dictionary)

In [ ]:
import os
os.getcwd()

In [ ]:
import ingestion as ing
import importlib
importlib.reload(ing)

In [ ]:
#val_dict = ing.fetch_socrata_metadata(ing.PROPERTY_VALUATION_ID, "valuation")
print(val_dict)

Wrote data dictionary (139 columns) -> data\processed\valuation_data_dictionary.csv
shape: (139, 4)
┌────────────┬────────────┬──────────────┬─────────────┐
│ name       ┆ fieldName  ┆ dataTypeName ┆ description │
│ ---        ┆ ---        ┆ ---          ┆ ---         │
│ str        ┆ str        ┆ str          ┆ str         │
╞════════════╪════════════╪══════════════╪═════════════╡
│ PARID      ┆ parid      ┆ text         ┆             │
│ BORO       ┆ boro       ┆ number       ┆             │
│ BLOCK      ┆ block      ┆ number       ┆             │
│ LOT        ┆ lot        ┆ number       ┆             │
│ EASEMENT   ┆ easement   ┆ text         ┆             │
│ …          ┆ …          ┆ …            ┆ …           │
│ PYTAXFLAG  ┆ pytaxflag  ┆ text         ┆             │
│ TENTAXFLAG ┆ tentaxflag ┆ text         ┆             │
│ CBNTAXFLAG ┆ cbntaxflag ┆ text         ┆             │
│ FINTAXFLAG ┆ fintaxflag ┆ text         ┆             │
│ CURTAXFLAG ┆ curtaxflag ┆ text         ┆             │
└────────────┴────────────┴──────────────┴─────────────┘

## Step 2: Pull current sales data

In [22]:
# Pull the current/annualized sales data (~846K rows)
# This saves a file called sales_annualized_raw.parquet inside data/processed/.
ing.pull_calendar_sales_annualized()

Pulling NYC Citywide Annualized Calendar Sales Update...
  fetched 50,000 rows so far...
  fetched 100,000 rows so far...
  fetched 150,000 rows so far...
  fetched 200,000 rows so far...
  fetched 250,000 rows so far...
  fetched 300,000 rows so far...
  fetched 350,000 rows so far...
  fetched 400,000 rows so far...
  fetched 450,000 rows so far...
  fetched 500,000 rows so far...
  fetched 550,000 rows so far...
  fetched 600,000 rows so far...
  fetched 650,000 rows so far...
  fetched 700,000 rows so far...
  fetched 750,000 rows so far...
  fetched 800,000 rows so far...
  fetched 850,000 rows so far...
  845,607 rows -> data\processed\sales_annualized_raw.parquet

shape: (845_607, 28)
┌─────────┬─────────────┬────────────┬────────────┬───┬─────────┬────────────┬────────────┬────────┐
│ borough ┆ neighborhoo ┆ building_c ┆ tax_class_ ┆ … ┆ bin     ┆ bbl        ┆ census_tra ┆ nta    │
│ ---     ┆ d           ┆ lass_categ ┆ as_of_fina ┆   ┆ ---     ┆ ---        ┆ ct_2020    ┆ ---    │
│ str     ┆ ---         ┆ ory        ┆ l_roll     ┆   ┆ str     ┆ str        ┆ ---        ┆ str    │
│         ┆ str         ┆ ---        ┆ ---        ┆   ┆         ┆            ┆ str        ┆        │
│         ┆             ┆ str        ┆ str        ┆   ┆         ┆            ┆            ┆        │
╞═════════╪═════════════╪════════════╪════════════╪═══╪═════════╪════════════╪════════════╪════════╡
│ 1       ┆ CHINATOWN   ┆ 47 CONDO   ┆ 4          ┆ … ┆ 1088222 ┆ 1001727504 ┆ 31         ┆ MN0102 │
│         ┆             ┆ NON-BUSINE ┆            ┆   ┆         ┆            ┆            ┆        │
│         ┆             ┆ SS STORAGE ┆            ┆   ┆         ┆            ┆            ┆        │
│ 1       ┆ EAST        ┆ 10 COOPS - ┆ 2          ┆ … ┆ 1006622 ┆ 1004610024 ┆ 38         ┆ MN0303 │
│         ┆ VILLAGE     ┆ ELEVATOR   ┆            ┆   ┆         ┆            ┆            ┆        │
│         ┆             ┆ APARTMENTS ┆            ┆   ┆         ┆            ┆            ┆        │
│ 1       ┆ FASHION     ┆ 21 OFFICE  ┆ 4          ┆ … ┆ 1014284 ┆ 1007790023 ┆ 95         ┆ MN0501 │
│         ┆             ┆ BUILDINGS  ┆            ┆   ┆         ┆            ┆            ┆        │
│ 1       ┆ FASHION     ┆ 13 CONDOS  ┆ 2          ┆ … ┆ 1090404 ┆ 1008417501 ┆ 84         ┆ MN0502 │
│         ┆             ┆ - ELEVATOR ┆            ┆   ┆         ┆            ┆            ┆        │
│         ┆             ┆ APARTMENT… ┆            ┆   ┆         ┆            ┆            ┆        │
│ 1       ┆ EAST        ┆ 10 COOPS - ┆ 2          ┆ … ┆ 1005762 ┆ 1004310031 ┆ 32         ┆ MN0303 │
│         ┆ VILLAGE     ┆ ELEVATOR   ┆            ┆   ┆         ┆            ┆            ┆        │
│         ┆             ┆ APARTMENTS ┆            ┆   ┆         ┆            ┆            ┆        │
│ …       ┆ …           ┆ …          ┆ …          ┆ … ┆ …       ┆ …          ┆ …          ┆ …      │
│ 5       ┆ WOODROW     ┆ 02 TWO     ┆ 1          ┆ … ┆ 5150506 ┆ 5073490053 ┆ 22601      ┆ SI0304 │
│         ┆             ┆ FAMILY     ┆            ┆   ┆         ┆            ┆            ┆        │
│         ┆             ┆ DWELLINGS  ┆            ┆   ┆         ┆            ┆            ┆        │
│ 5       ┆ WOODROW     ┆ 02 TWO     ┆ 1          ┆ … ┆ 5155237 ┆ 5073590013 ┆ 22601      ┆ SI0304 │
│         ┆             ┆ FAMILY     ┆            ┆   ┆         ┆            ┆            ┆        │
│         ┆             ┆ DWELLINGS  ┆            ┆   ┆         ┆            ┆            ┆        │
│ 5       ┆ WOODROW     ┆ 05 TAX     ┆ 1B         ┆ … ┆ 5000000 ┆ 5069980014 ┆ 20803      ┆ SI0304 │
│         ┆             ┆ CLASS 1    ┆            ┆   ┆         ┆            ┆            ┆        │
│         ┆             ┆ VACANT     ┆            ┆   ┆         ┆            ┆            ┆        │
│         ┆             ┆ LAND       ┆            ┆   ┆         ┆            ┆            ┆        │
│ 5       ┆ WOODROW     ┆ 21 OFFICE  ┆ 4          ┆ … ┆ 5149151 ┆ 5070110001 ┆ 20803      ┆ SI0304 │
│         ┆             ┆ BUILDINGS  ┆            ┆   ┆         ┆            ┆            ┆        │
│ 5       ┆ WOODROW     ┆ 21 OFFICE  ┆ 4          ┆ … ┆ 5128812 ┆ 5072670081 ┆ 22601      ┆ SI0304 │
│         ┆             ┆ BUILDINGS  ┆            ┆   ┆         ┆            ┆            ┆        │
└─────────┴─────────────┴────────────┴────────────┴───┴─────────┴────────────┴────────────┴────────┘

## Step 3: Load archive sales data

In [23]:
# Load and combine the two archive CSVs (2003–2015)
# This saves sales_archive_raw.parquet, and will print out any column mismatches between the two files if it finds any
ing.load_and_standardize_archive()

Loading and standardizing archive sales files...
  2003_2012: 1,041,423 rows, 21 columns
  2013_2015: 270,107 rows, 21 columns
  combined archive: 1,311,530 rows -> data\processed\sales_archive_raw.parquet

shape: (1_311_530, 21)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ borough ┆ neighborho ┆ building_ ┆ tax_class ┆ … ┆ tax_class ┆ building_ ┆ sale_pric ┆ sale_date │
│ ---     ┆ od         ┆ class_cat ┆ _at_prese ┆   ┆ _at_time_ ┆ class_at_ ┆ e         ┆ ---       │
│ i64     ┆ ---        ┆ egory     ┆ nt        ┆   ┆ of_sale   ┆ time_of_s ┆ ---       ┆ str       │
│         ┆ str        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ale       ┆ i64       ┆           │
│         ┆            ┆ str       ┆ str       ┆   ┆ i64       ┆ ---       ┆           ┆           │
│         ┆            ┆           ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1       ┆ ALPHABET   ┆ 02  TWO   ┆ 1         ┆ … ┆ 1         ┆ B9        ┆ 1800000   ┆ 1/22/2003 │
│         ┆ CITY       ┆ FAMILY    ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ HOMES     ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ …         ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1       ┆ ALPHABET   ┆ 07        ┆ 2A        ┆ … ┆ 2         ┆ C3        ┆ 0         ┆ 12/18/200 │
│         ┆ CITY       ┆ RENTALS - ┆           ┆   ┆           ┆           ┆           ┆ 3         │
│         ┆            ┆ WALKUP    ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ APARTMENT ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ …         ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1       ┆ ALPHABET   ┆ 07        ┆ 2A        ┆ … ┆ 2         ┆ C3        ┆ 0         ┆ 12/18/200 │
│         ┆ CITY       ┆ RENTALS - ┆           ┆   ┆           ┆           ┆           ┆ 3         │
│         ┆            ┆ WALKUP    ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ APARTMENT ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ …         ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1       ┆ ALPHABET   ┆ 07        ┆ 2B        ┆ … ┆ 2         ┆ C4        ┆ 426000    ┆ 10/23/200 │
│         ┆ CITY       ┆ RENTALS - ┆           ┆   ┆           ┆           ┆           ┆ 3         │
│         ┆            ┆ WALKUP    ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ APARTMENT ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ …         ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1       ┆ ALPHABET   ┆ 07        ┆ 2         ┆ … ┆ 2         ┆ C1        ┆ 0         ┆ 2/28/2003 │
│         ┆ CITY       ┆ RENTALS - ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ WALKUP    ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ APARTMENT ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ …         ┆           ┆   ┆           ┆           ┆           ┆           │
│ …       ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 5       ┆ WOODROW    ┆ 02  TWO   ┆ 1         ┆ … ┆ 1         ┆ B2        ┆ 0         ┆ 2/19/2015 │
│         ┆            ┆ FAMILY    ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ DWELLINGS ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ …         ┆           ┆   ┆           ┆           ┆           ┆           │
│ 5       ┆ WOODROW    ┆ 02  TWO   ┆ 1         ┆ … ┆ 1         ┆ B2        ┆ 825000    ┆ 9/17/2015 │
│         ┆            ┆ FAMILY    ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ DWELLINGS ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ …         ┆           ┆   ┆           ┆           ┆           ┆           │
│ 5       ┆ WOODROW    ┆ 02  TWO   ┆ 1         ┆ … ┆ 1         ┆ B9        ┆ 490000    ┆ 1/15/2015 │
│         ┆            ┆ FAMILY    ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ DWELLINGS ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ …         ┆           ┆   ┆           ┆           ┆           ┆           │
│ 5       ┆ WOODROW    ┆ 02  TWO   ┆ 1         ┆ … ┆ 1         ┆ B9        ┆ 10        ┆ 11/6/2015 │
│         ┆            ┆ FAMILY    ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ DWELLINGS ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ …         ┆           ┆   ┆           ┆           ┆           ┆           │
│ 5       ┆ WOODROW    ┆ 05  TAX   ┆ 1B        ┆ … ┆ 1         ┆ V0        ┆ 0         ┆ 10/7/2015 │
│         ┆            ┆ CLASS 1   ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ VACANT    ┆           ┆   ┆           ┆           ┆           ┆           │
│         ┆            ┆ LAND   …  ┆           ┆   ┆           ┆           ┆           ┆           │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Step 4: Combine into master sales file

In [25]:
# Combine steps 1 and 2 into one master sales file
# This saves sales_master.parquet — this is the full, combined sales history in one file
ing.build_master_sales_file()

Building master sales file (archive + annualized)...
  columns only in archive: {'ease_ment'}
  columns only in annualized: {'community_board', 'council_district', 'bin', 'bbl', 'longitude', 'latitude', 'census_tract_2020', 'nta'}
  master sales file: 2,157,137 rows -> data\processed\sales_master.parquet

shape: (2_157_137, 29)
┌─────────┬─────────────┬────────────┬────────────┬───┬─────────┬────────────┬────────────┬────────┐
│ borough ┆ neighborhoo ┆ building_c ┆ tax_class_ ┆ … ┆ bin     ┆ bbl        ┆ census_tra ┆ nta    │
│ ---     ┆ d           ┆ lass_categ ┆ as_of_fina ┆   ┆ ---     ┆ ---        ┆ ct_2020    ┆ ---    │
│ str     ┆ ---         ┆ ory        ┆ l_roll     ┆   ┆ str     ┆ str        ┆ ---        ┆ str    │
│         ┆ str         ┆ ---        ┆ ---        ┆   ┆         ┆            ┆ str        ┆        │
│         ┆             ┆ str        ┆ str        ┆   ┆         ┆            ┆            ┆        │
╞═════════╪═════════════╪════════════╪════════════╪═══╪═════════╪════════════╪════════════╪════════╡
│ 1       ┆ ALPHABET    ┆ 02  TWO    ┆ 1          ┆ … ┆ null    ┆ null       ┆ null       ┆ null   │
│         ┆ CITY        ┆ FAMILY     ┆            ┆   ┆         ┆            ┆            ┆        │
│         ┆             ┆ HOMES      ┆            ┆   ┆         ┆            ┆            ┆        │
│         ┆             ┆ …          ┆            ┆   ┆         ┆            ┆            ┆        │
│ 1       ┆ ALPHABET    ┆ 07         ┆ 2A         ┆ … ┆ null    ┆ null       ┆ null       ┆ null   │
│         ┆ CITY        ┆ RENTALS -  ┆            ┆   ┆         ┆            ┆            ┆        │
│         ┆             ┆ WALKUP     ┆            ┆   ┆         ┆            ┆            ┆        │
│         ┆             ┆ APARTMENT… ┆            ┆   ┆         ┆            ┆            ┆        │
│ 1       ┆ ALPHABET    ┆ 07         ┆ 2A         ┆ … ┆ null    ┆ null       ┆ null       ┆ null   │
│         ┆ CITY        ┆ RENTALS -  ┆            ┆   ┆         ┆            ┆            ┆        │
│         ┆             ┆ WALKUP     ┆            ┆   ┆         ┆            ┆            ┆        │
│         ┆             ┆ APARTMENT… ┆            ┆   ┆         ┆            ┆            ┆        │
│ 1       ┆ ALPHABET    ┆ 07         ┆ 2B         ┆ … ┆ null    ┆ null       ┆ null       ┆ null   │
│         ┆ CITY        ┆ RENTALS -  ┆            ┆   ┆         ┆            ┆            ┆        │
│         ┆             ┆ WALKUP     ┆            ┆   ┆         ┆            ┆            ┆        │
│         ┆             ┆ APARTMENT… ┆            ┆   ┆         ┆            ┆            ┆        │
│ 1       ┆ ALPHABET    ┆ 07         ┆ 2          ┆ … ┆ null    ┆ null       ┆ null       ┆ null   │
│         ┆ CITY        ┆ RENTALS -  ┆            ┆   ┆         ┆            ┆            ┆        │
│         ┆             ┆ WALKUP     ┆            ┆   ┆         ┆            ┆            ┆        │
│         ┆             ┆ APARTMENT… ┆            ┆   ┆         ┆            ┆            ┆        │
│ …       ┆ …           ┆ …          ┆ …          ┆ … ┆ …       ┆ …          ┆ …          ┆ …      │
│ 5       ┆ WOODROW     ┆ 02 TWO     ┆ 1          ┆ … ┆ 5150506 ┆ 5073490053 ┆ 22601      ┆ SI0304 │
│         ┆             ┆ FAMILY     ┆            ┆   ┆         ┆            ┆            ┆        │
│         ┆             ┆ DWELLINGS  ┆            ┆   ┆         ┆            ┆            ┆        │
│ 5       ┆ WOODROW     ┆ 02 TWO     ┆ 1          ┆ … ┆ 5155237 ┆ 5073590013 ┆ 22601      ┆ SI0304 │
│         ┆             ┆ FAMILY     ┆            ┆   ┆         ┆            ┆            ┆        │
│         ┆             ┆ DWELLINGS  ┆            ┆   ┆         ┆            ┆            ┆        │
│ 5       ┆ WOODROW     ┆ 05 TAX     ┆ 1B         ┆ … ┆ 5000000 ┆ 5069980014 ┆ 20803      ┆ SI0304 │
│         ┆             ┆ CLASS 1    ┆            ┆   ┆         ┆            ┆            ┆        │
│         ┆             ┆ VACANT     ┆            ┆   ┆         ┆            ┆            ┆        │
│         ┆             ┆ LAND       ┆            ┆   ┆         ┆            ┆            ┆        │
│ 5       ┆ WOODROW     ┆ 21 OFFICE  ┆ 4          ┆ … ┆ 5149151 ┆ 5070110001 ┆ 20803      ┆ SI0304 │
│         ┆             ┆ BUILDINGS  ┆            ┆   ┆         ┆            ┆            ┆        │
│ 5       ┆ WOODROW     ┆ 21 OFFICE  ┆ 4          ┆ … ┆ 5128812 ┆ 5072670081 ┆ 22601      ┆ SI0304 │
│         ┆             ┆ BUILDINGS  ┆            ┆   ┆         ┆            ┆            ┆        │
└─────────┴─────────────┴────────────┴────────────┴───┴─────────┴────────────┴────────────┴────────┘

## Step 5: Pull valuation data

In [ ]:
# Pull the valuation data (the big one — will take the longest)
# This one prints progress as it goes (50,000 rows fetched..., 100,000 rows fetched..., etc.) so you can see it's working. It saves valuation_master.parquet.
ing.pull_property_valuation()

In [6]:
# check PLUTO columns
ing.fetch_socrata_metadata(ing.PLUTO_ID, "pluto")
ing.check_pluto_columns()

Wrote data dictionary (108 columns) -> data\processed\pluto_data_dictionary.csv
  All candidate PLUTO columns are valid.

['bbl',
 'borough',
 'block',
 'lot',
 'address',
 'latitude',
 'longitude',
 'cd',
 'council',
 'zipcode',
 'bct2020',
 'bldgclass',
 'yearbuilt',
 'lotarea',
 'bldgarea',
 'unitsres',
 'unitstotal',
 'numbldgs']

In [7]:
# ingest PLUTO data
ing.pull_pluto()

Pulling PLUTO (Primary Land Use Tax Lot Output)...
  fetched 50,000 rows so far...
  fetched 100,000 rows so far...
  fetched 150,000 rows so far...
  fetched 200,000 rows so far...
  fetched 250,000 rows so far...
  fetched 300,000 rows so far...
  fetched 350,000 rows so far...
  fetched 400,000 rows so far...
  fetched 450,000 rows so far...
  fetched 500,000 rows so far...
  fetched 550,000 rows so far...
  fetched 600,000 rows so far...
  fetched 650,000 rows so far...
  fetched 700,000 rows so far...
  fetched 750,000 rows so far...
  fetched 800,000 rows so far...
  fetched 850,000 rows so far...
  fetched 900,000 rows so far...
  858,284 rows -> data\processed\pluto_raw.parquet

shape: (858_284, 18)
┌─────────────────────┬─────────┬───────┬─────┬───┬──────────┬──────────┬────────────┬──────────┐
│ bbl                 ┆ borough ┆ block ┆ lot ┆ … ┆ bldgarea ┆ unitsres ┆ unitstotal ┆ numbldgs │
│ ---                 ┆ ---     ┆ ---   ┆ --- ┆   ┆ ---      ┆ ---      ┆ ---        ┆ ---      │
│ str                 ┆ str     ┆ str   ┆ str ┆   ┆ str      ┆ str      ┆ str        ┆ str      │
╞═════════════════════╪═════════╪═══════╪═════╪═══╪══════════╪══════════╪════════════╪══════════╡
│ 4087860042.00000000 ┆ QN      ┆ 8786  ┆ 42  ┆ … ┆ 1864     ┆ 1        ┆ 1          ┆ 2        │
│ 4087860046.00000000 ┆ QN      ┆ 8786  ┆ 46  ┆ … ┆ 960      ┆ 1        ┆ 1          ┆ 1        │
│ 4087860051.00000000 ┆ QN      ┆ 8786  ┆ 51  ┆ … ┆ 1068     ┆ 1        ┆ 1          ┆ 1        │
│ 4087980002.00000000 ┆ QN      ┆ 8798  ┆ 2   ┆ … ┆ 960      ┆ 1        ┆ 1          ┆ 2        │
│ 4087980003.00000000 ┆ QN      ┆ 8798  ┆ 3   ┆ … ┆ 960      ┆ 1        ┆ 1          ┆ 2        │
│ …                   ┆ …       ┆ …     ┆ …   ┆ … ┆ …        ┆ …        ┆ …          ┆ …        │
│ 4087850033.00000000 ┆ QN      ┆ 8785  ┆ 33  ┆ … ┆ 1188     ┆ 1        ┆ 1          ┆ 1        │
│ 5030400083.00000000 ┆ SI      ┆ 3040  ┆ 83  ┆ … ┆ 1700     ┆ 2        ┆ 2          ┆ 2        │
│ 4087850034.00000000 ┆ QN      ┆ 8785  ┆ 34  ┆ … ┆ 1188     ┆ 1        ┆ 1          ┆ 2        │
│ 4087850035.00000000 ┆ QN      ┆ 8785  ┆ 35  ┆ … ┆ 1188     ┆ 1        ┆ 1          ┆ 1        │
│ 4087860040.00000000 ┆ QN      ┆ 8786  ┆ 40  ┆ … ┆ 960      ┆ 1        ┆ 1          ┆ 1        │
└─────────────────────┴─────────┴───────┴─────┴───┴──────────┴──────────┴────────────┴──────────┘